name: fchan
description: 4chan client on Flutter.

version: 0.6.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.2+3
  get_it: 5.0.0

  sqflite: ^1.3.1+1

  http: 0.12.2
  flutter_html: ^1.0.0
  url_launcher: ^5.6.0

  path_provider: ^1.6.18

  flutter_cache_manager: ^1.4.2
  cached_network_image: ^2.3.2+1

  flutter_staggered_grid_view: ^0.3.2

  clipboard: ^0.1.2+8

  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.5.0

  build_runner: ^1.10.0

  effective_dart: ^1.3.0

  test: ^1.15.4
  mockito: 4.0.0

  dart_enum_to_string_check: ^0.6.2

flutter:
  uses-material-design: true
