name: fchan
description: 4chan client on Flutter.
version: 0.6.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0
  get_it: ^6.1.1

  sqflite: ^2.0.0+3

  http: ^0.13.1
  flutter_html: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.3

  path_provider: ^2.0.1

  flutter_cache_manager: ^3.0.1
  cached_network_image: ^3.0.0

  flutter_staggered_grid_view: ^0.4.0

  clipboard: ^0.1.3

  package_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  return it back when null safety becomes enable
  #  test_coverage: ^0.5.0

  build_runner: ^1.10.0

  test: ^1.16.5
  mockito: ^5.0.5

  effective_dart: ^1.3.1
  dart_enum_to_string_check: ^0.7.2
  dart_code_metrics: ^3.2.2

flutter:
  uses-material-design: true
